version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/Messiah-Marketplace

jobs:
  eas_build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
          - run: eas login $LOGIN_USERNAME $LOGIN_PASSWORD
      - run:
          name: Trigger build
          command: npx eas-cli build --platform all --non-interactive

workflows:
  build_app:
    jobs:
      - eas_build:
          filters:
            branches:
              only: main